# Generated by Django 4.2.2 on 2023-06-28 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0006_comment_posted_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="")),
                ("url", models.URLField()),
                ("name", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "banner",
                "verbose_name_plural": "banners",
            },
        ),
    ]
