# Generated by Django 4.2.2 on 2023-06-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0008_banner_delete_adbanner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="banner",
            options={"verbose_name": "banner", "verbose_name_plural": "banners"},
        ),
        migrations.AddField(
            model_name="news",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="news",
            name="source",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="news",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
